train_file: ['data/mscoco_train_albef.json',
               'data/vgnococo_albef.json',
               'data/cc_albef.json',
               'data/mscoco_val_albef.json',
               'data/sbu_albef.json'
               ]
# each train_file (json) contains a python list where each item is {'image': img_path, 'caption': text or list_of_text }               
bert_config: 'configs/config_bert_no_cross.json'
read_local_data: False
mid_cross: True

image_res: 256
vision_width: 768
embed_dim: 256
batch_size: 32
temp: 0.07
mlm_probability: 0.15
#queue_size: 65536
queue_size: 66048
momentum: 0.995
alpha: 0.4

optimizer: {opt: adamW, lr1: 1e-4, lr2: 1e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-5, epochs: 30, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-6, warmup_epochs: 20, cooldown_epochs: 0}







