train_file: ["//nas-alinlp/lcl193798/data_renm/VCR/train.jsonl"]
val_file: ["//nas-alinlp/lcl193798/data_renm/VCR/val.jsonl"]
test_file: ["//nas-alinlp/lcl193798/data_renm/VCR/test.jsonl"]

read_local_data: True
mid_cross: True
bert_config: 'configs/config_bert.json'
vcr_root: "//nas-alinlp/lcl193798/data_renm/VCR/vcr1images_label"
image_res: 392
batch_size_train: 32
vision_width: 1024
distill: True
clip_name: "ViT-L-14"
batch_size_test: 16 
k_test: 128

alpha: 0.4
warm_up: True

eos: '[SEP]'


optimizer: {opt: adamW, lr1: 2e-5, lr2: 5e-6, lr3: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 8, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}

# optimizer: {opt: adamW, lr1: 5e-5, lr2: 5e-5, lr3: 1e-3, weight_decay: 0.02}
# schedular: {sched: cosine, lr: 5e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 5e-5, warmup_epochs: 1, cooldown_epochs: 0}


noop_idx: 0
stack_length: 8
h_feature: 28
w_feature: 28
replace_fusion: False
hidden_dropout_prob: 0.1
layout_vocab_size: 9
internal_dim: 768
controller_nodes: 8
module_names: ['_NoOp',
             '_Find',   
             '_Transform',
             '_Filter',
             '_And',
             "_Or",
             "_Scene",
             "_DescribeOne",
             "_DescribeTwo"
             ]

guard_stack_ptr: True
keep_describe_stack: True
validate_module: False
use_hard_sharpen_ptr: False
soft_sharpen_temp_prt: 0.2

vqa_loss_weight: 1.0
layout_loss_weight: 1.0
use_gt_layout: False



