# train_file: ['/nas-alinlp/lcl193798/albef/data/vqa_ocr_object/vqa_train_ocr.json',
#              '/nas-alinlp/lcl193798/albef/data/vqa_ocr_object/vqa_nominival_ocr.json',
#             #  '/nas-alinlp/lcl193798/albef/data/vg_qa.json',
#              '/nas-alinlp/lcl193798/albef/data/vqa_ocr_object/vqa_minival_ocr.json']
train_file: ['/nas-alinlp/lcl193798/albef/data/vqa_ocr_object/vqa_train_ocr_program.json',
             '/nas-alinlp/lcl193798/albef/data/vqa_ocr_object/vqa_nominival_ocr_program.json',
            #  '/nas-alinlp/lcl193798/albef/data/vg_qa.json',
             '/nas-alinlp/lcl193798/albef/data/vqa_ocr_object/vqa_minival_ocr.json']
# train_file: [ '/nas-alinlp/lcl193798/albef/data/vg_qa.json',]
val_file: ['/nas-alinlp/lcl193798/albef/data/vqa_ocr_object/vqa_minival_ocr.json']
test_file: ['/nas-alinlp/lcl193798/albef/data/vqa_ocr_object/vqa_test_ocr.json']
label_file: ['/nas-alinlp/lcl193798/albef/data/vqa_ocr_object/minival.json']
answer_list: '/nas-alinlp/lcl193798/albef/data/answer_list.json'
layout_file: ['/nas-alinlp/lcl193798/data_renm/mcren/Multi-Modal/VQA/stacknmn_v2/vqa/data_process/v2_gt_layout_train2014_new_parse.npy',
             '/nas-alinlp/lcl193798/data_renm/mcren/Multi-Modal/VQA/stacknmn_v2/vqa/data_process/v2_gt_layout_val2014_new_parse.npy']    
             
read_local_data: True
#vqa_root: '/home/public/sandbox/mm_feature/coco_2014/'
#vg_root: '/home/public/sandbox/mm_feature/visual_genome/'
vqa_root: '/nas-alinlp/lcl193798/mm_feature/coco_2014/'
vg_root: '/nas-alinlp/lcl193798/mm_feature/visual_genome/'
gqa_root: '/nas-alinlp/lcl193798/mm_feature/'
mid_cross: True

bert_config: 'configs/config_bert.json'

image_res: 224
batch_size_train: 32
vision_width: 1024
distill: True
clip_name: "ViT-L-14"
#image_res: 576
#batch_size_train: 8 
batch_size_test: 16 
k_test: 128

alpha: 0.4
warm_up: True

eos: '[SEP]'


optimizer: {opt: adamW, lr1: 2e-5, lr2: 5e-6, lr3: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 8, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}

# optimizer: {opt: adamW, lr1: 5e-5, lr2: 5e-5, lr3: 1e-3, weight_decay: 0.02}
# schedular: {sched: cosine, lr: 5e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 5e-5, warmup_epochs: 1, cooldown_epochs: 0}


noop_idx: 0
stack_length: 8
h_feature: 16
w_feature: 16
replace_fusion: False
hidden_dropout_prob: 0.1
answer_vocab_size: 3128
layout_vocab_size: 9
internal_dim: 768
controller_nodes: 12
module_names: ['_NoOp',
             '_Find',   
             '_Transform',
             '_Filter',
             '_And',
             "_Or",
             "_Scene",
             "_DescribeOne",
             "_DescribeTwo"
             ]

guard_stack_ptr: True
keep_describe_stack: True
validate_module: False
use_hard_sharpen_ptr: False
soft_sharpen_temp_prt: 0.2

vqa_loss_weight: 1.0
layout_loss_weight: 1.0
use_gt_layout: False



